In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('train.csv')
data


0.388442524176399  0.945130525411413  0.224574166698005  \
0              0.005577           0.212454           0.966685   
1              0.293708           0.839556           0.087624   
2              0.273974           0.196409           0.944799   
3              0.855060           0.548291           0.723422   
4              0.145363           0.868038           0.422707   
...                 ...                ...                ...   
2995           0.582766           0.082229           0.124548   
2996           0.069877           0.619358           0.943559   
2997           0.019215           0.419974           0.241260   
2998           0.542132           0.393701           0.562562   
2999           0.392494           0.811628           0.825566   

      0.179739355943136  0.162540288887288  0.396774460453791  \
0              0.732933           0.219441           0.630520   
1              0.004181           0.280067           0.152203   
2              0.290177           0.591548           0.538663   
3              0.759935           0.834415           0.294425   
4              0.720720           0.006682           0.543664   
...                 ...                ...                ...   
2995           0.994453           0.067374           0.010687   
2996           0.853897           0.758349           0.343341   
2997           0.877471           0.624322           0.448705   
2998           0.930131           0.604183           0.213786   
2999           0.887180           0.706848           0.260906   

      0.652745265274972  0.690031100185927  0.031527897153938  1  
0              0.592556           0.498985           0.179090  0  
1              0.030886           0.421273           0.676549  1  
2              0.008313           0.391987           0.664255  1  
3              0.008644           0.146727           0.430659  1  
4              0.373562           0.806251           0.777380  0  
...                 ...                ...                ... ..  
2995           0.676720           0.496930           0.222234  1  
2996           0.268033           0.527860           0.809984  0  
2997           0.847957           0.944061           0.699582  0  
2998           0.494371           0.922856           0.508638  1  
2999           0.402526           0.802987           0.419927  1  

[3000 rows x 10 columns]

In [2]:
row1 = np.ones((len(data), 1))

X = data.iloc[:, :-1].values
X = np.hstack((row1, X))

Y = data.iloc[:, -1].values.reshape(-1, 1)


print("Feature Matrix (X):")
print(X)
print("\nTarget Variable (Y):")
print(Y)


Feature Matrix (X):
[[1.         0.00557654 0.21245405 ... 0.59255628 0.49898456 0.17908995]
 [1.         0.29370811 0.83955569 ... 0.03088631 0.42127346 0.67654894]
 [1.         0.27397374 0.19640879 ... 0.00831341 0.39198746 0.66425476]
 ...
 [1.         0.01921512 0.41997374 ... 0.84795664 0.94406122 0.69958201]
 [1.         0.54213243 0.39370136 ... 0.49437143 0.92285587 0.50863825]
 [1.         0.39249439 0.81162794 ... 0.40252598 0.8029868  0.41992697]]

Target Variable (Y):
[[0]
 [1]
 [1]
 ...
 [0]
 [1]
 [1]]


In [3]:
m, n = X.shape
print("Number of rows (m):", m)
print("Number of columns (n):", n)


Number of rows (m): 3000
Number of columns (n): 10


In [4]:
def logisticFunc(z):
    return 1 / (1 + np.exp(-z))

def h_w(x, w):
    y = logisticFunc(np.dot(x, w))
    return y

logisticValue = logisticFunc(5)
logisticValue = logisticFunc(np.ones((5, 1)) * 0.5)
logisticValue = logisticFunc(np.ones((5, 3)) * 0.5)

x_sample = np.ones((1, 5)) * 0.5
w_sample = np.ones((5, 1)) * 0.2
y_pred_sample = h_w(x_sample, w_sample)
assert round(y_pred_sample[0][0], 3) == 0.622

x_sample = np.ones((3, 5)) * 0.5
w_sample = np.ones((5, 1)) * 0.2
y_pred_sample = h_w(x_sample, w_sample)
assert round(y_pred_sample[0][0], 3) == 0.622

y_pred_sample


array([[0.62245933],
       [0.62245933],
       [0.62245933]])

In [5]:
def costFunc_iter(y_i, x_i, w):
    h_w_i = h_w(x_i, w)
    return (y_i * np.log(h_w_i) + (1 - y_i) * np.log(1 - h_w_i))

x_sample = np.ones((1, 5)) * 0.5
w_sample = np.ones((5, 1)) * 0.2
y_sample = 1
J_iter_sample = costFunc_iter(y_sample, x_sample, w_sample)

def costFunc(Y_in, X_in, w_in):
    h_w_values = h_w(X_in, w_in)
    cost_values = Y_in * np.log(h_w_values) + (1 - Y_in) * np.log(1 - h_w_values)
    return -np.mean(cost_values)

X_sample = np.ones((2, 5)) * 0.5
w_sample = np.ones((5, 1)) * 0.2
Y_sample = np.ones((2, 1)) 
J_sample = costFunc(Y_sample, X_sample, w_sample)
assert round(J_sample, 3) == 0.474
J_sample


0.47407698418010663

In [9]:
alpha=0.001
eps=0.00001
iteration=10000
np.random.seed(0)
W=np.random.rand(n,1)
W=W.reshape(len(W),1)
Cost=10e10
Cost_new=0
m=len(X)
print(m)
import pdb

def compute_cost(X, y, W):
    m = y.shape[0]
    h = sigmoid(np.dot(X, W))
    cost = -(1/m) * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
    return cost

while(True):
    
    
    # Make Y prediction
#     Y_Pred=X.dot(W)
    Y_Pred = h_w(X,W)
#     print(Y_Pred)
    # W calculation step
    W_new = (W - X.transpose().dot(Y_Pred - Y)*alpha/(m))
    
#     print(W_new)
    #print(iteration, W_new)
    # W error calculation
    W_err = W_new - W
    Cost_new=costFunc(Y,X,W)
    Cost_err=abs(Cost_new-Cost)
#     print(W_err)
    # Checking termination condition. 
    is_all_w_err_lt_eps = True #is W_err <eps for all elements ex eps 5, W= 1,2,6,4
    if(abs(Cost_err)<eps):
        break
#     for w_err in W_err:
#         if abs(w_err) > eps: #Continue, W update
#             is_all_w_err_lt_eps = False
#         else: # DO NOTHING
#             pass
#     if is_all_w_err_lt_eps: #Stop if error is below threshold
#         break

    Cost=compute_cost()
    W=W_new
    
#     Cost.append(*costFunc(Y,X,W))
    
#     print(iteration, Cost[iteration])
    iteration=iteration+1
    if iteration%100==0 :
        print(iteration, '=', Cost, end =' \n')


3000
10100 = 0.5763904023686819 
10200 = 0.5706102167649347 
10300 = 0.5649503684670741 
10400 = 0.5594124833643762 
10500 = 0.5539980392467794 
10600 = 0.5487083561983859 
10700 = 0.543544587547167 
10800 = 0.5385077114760871 
10900 = 0.533598523398346 
11000 = 0.5288176291951161 
11100 = 0.5241654394079888 
11200 = 0.519642164470348 
11300 = 0.5152478110521458 
11400 = 0.5109821795811601 
11500 = 0.5068448629909393 
11600 = 0.5028352467315039 
11700 = 0.4989525100637104 
11800 = 0.4951956286423078 
11900 = 0.49156337837641695 
12000 = 0.48805434053980723 
12100 = 0.48466690808725027 
12200 = 0.4813992931177627 
12300 = 0.4782495354110285 
12400 = 0.4752155119500311 
12500 = 0.472294947331193 
12600 = 0.46948542495336354 
12700 = 0.4667843988689796 
12800 = 0.46418920617480125 
12900 = 0.4616970798158521 
13000 = 0.4593051616745972 
13100 = 0.45701051581793695 
13200 = 0.4548101417771762 
13300 = 0.4527009877406249 
13400 = 0.45067996354470113 
13500 = 0.4487439533571432 
13600 = 0.44